# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 651)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.play_btn = QtWidgets.QPushButton(self.centralwidget)
        self.play_btn.setGeometry(QtCore.QRect(490, 370, 75, 23))
        self.play_btn.setObjectName("play_btn")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 281, 651))
        self.listWidget.setObjectName("listWidget")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(350, 322, 401, 20))
        self.horizontalSlider.setStyleSheet("\n"
"     QSlider::add-page:Horizontal\n"
"     {     \n"
"        background-color: rgb(87, 97, 106);\n"
"        height:4px;\n"
"     }\n"
"     QSlider::sub-page:Horizontal \n"
"    {\n"
"        background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(231,80,229, 255), stop:1 rgba(7,208,255, 255));\n"
"        height:4px;\n"
"     }\n"
"    QSlider::groove:Horizontal \n"
"    {\n"
"        background:transparent;\n"
"        height:6px;\n"
"    }\n"
"    QSlider::handle:Horizontal \n"
"    {\n"
"        height: 30px;\n"
"        width:8px;\n"
"        border-image: url(:./resource/1.png);\n"
"        margin: -8 0px; \n"
"    }")
        self.horizontalSlider.setProperty("value", 0)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider.setTickInterval(2)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.before_btn = QtWidgets.QPushButton(self.centralwidget)
        self.before_btn.setGeometry(QtCore.QRect(350, 370, 75, 23))
        self.before_btn.setObjectName("before_btn")
        self.next_btn = QtWidgets.QPushButton(self.centralwidget)
        self.next_btn.setGeometry(QtCore.QRect(620, 370, 75, 23))
        self.next_btn.setObjectName("next_btn")
        self.input_btn = QtWidgets.QPushButton(self.centralwidget)
        self.input_btn.setGeometry(QtCore.QRect(620, 430, 75, 23))
        self.input_btn.setObjectName("input_btn")
        self.voice = QtWidgets.QSlider(self.centralwidget)
        self.voice.setGeometry(QtCore.QRect(510, 140, 22, 160))
        self.voice.setStyleSheet("")
        self.voice.setOrientation(QtCore.Qt.Vertical)
        self.voice.setObjectName("voice")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.voice, self.horizontalSlider)
        MainWindow.setTabOrder(self.horizontalSlider, self.before_btn)
        MainWindow.setTabOrder(self.before_btn, self.next_btn)
        MainWindow.setTabOrder(self.next_btn, self.input_btn)
        MainWindow.setTabOrder(self.input_btn, self.play_btn)
        MainWindow.setTabOrder(self.play_btn, self.listWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.play_btn.setText(_translate("MainWindow", "play"))
        self.before_btn.setText(_translate("MainWindow", "before"))
        self.next_btn.setText(_translate("MainWindow", "next"))
        self.input_btn.setText(_translate("MainWindow", "fileinput"))
