# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyMusicPlayer(object):
    def setupUi(self, MyMusicPlayer):
        MyMusicPlayer.setObjectName("MyMusicPlayer")
        MyMusicPlayer.resize(800, 651)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MyMusicPlayer.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MyMusicPlayer)
        self.centralwidget.setObjectName("centralwidget")
        self.play_btn = QtWidgets.QPushButton(self.centralwidget)
        self.play_btn.setGeometry(QtCore.QRect(490, 370, 75, 23))
        self.play_btn.setObjectName("play_btn")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 281, 651))
        self.listWidget.setObjectName("listWidget")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(350, 322, 401, 20))
        self.horizontalSlider.setStyleSheet("\n"
"     QSlider::add-page:Horizontal\n"
"     {     \n"
"        background-color: rgb(87, 97, 106);\n"
"        height:4px;\n"
"     }\n"
"     QSlider::sub-page:Horizontal \n"
"    {\n"
"        background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(231,80,229, 255), stop:1 rgba(7,208,255, 255));\n"
"        height:4px;\n"
"     }\n"
"    QSlider::groove:Horizontal \n"
"    {\n"
"        background:transparent;\n"
"        height:6px;\n"
"    }\n"
"    QSlider::handle:Horizontal \n"
"    {\n"
"        height: 30px;\n"
"        width:8px;\n"
"        border-image: url(:/resource/1.png);\n"
"        margin: -8 0px; \n"
"    }")
        self.horizontalSlider.setProperty("value", 0)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider.setTickInterval(2)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.before_btn = QtWidgets.QPushButton(self.centralwidget)
        self.before_btn.setGeometry(QtCore.QRect(350, 370, 75, 23))
        self.before_btn.setObjectName("before_btn")
        self.next_btn = QtWidgets.QPushButton(self.centralwidget)
        self.next_btn.setGeometry(QtCore.QRect(620, 370, 75, 23))
        self.next_btn.setObjectName("next_btn")
        self.input_btn = QtWidgets.QPushButton(self.centralwidget)
        self.input_btn.setGeometry(QtCore.QRect(620, 430, 75, 23))
        self.input_btn.setObjectName("input_btn")
        self.voice = QtWidgets.QSlider(self.centralwidget)
        self.voice.setGeometry(QtCore.QRect(510, 140, 22, 160))
        self.voice.setStyleSheet("")
        self.voice.setOrientation(QtCore.Qt.Vertical)
        self.voice.setObjectName("voice")
        self.played_time_lab = QtWidgets.QLabel(self.centralwidget)
        self.played_time_lab.setGeometry(QtCore.QRect(300, 320, 41, 31))
        self.played_time_lab.setObjectName("played_time_lab")
        self.len_time_lab = QtWidgets.QLabel(self.centralwidget)
        self.len_time_lab.setGeometry(QtCore.QRect(760, 320, 41, 31))
        self.len_time_lab.setObjectName("len_time_lab")
        self.order_list = QtWidgets.QComboBox(self.centralwidget)
        self.order_list.setGeometry(QtCore.QRect(490, 430, 81, 22))
        self.order_list.setObjectName("order_list")
        self.order_list.addItem("")
        self.order_list.addItem("")
        self.order_list.addItem("")
        self.order_list.addItem("")
        self.order_list.addItem("")
        MyMusicPlayer.setCentralWidget(self.centralwidget)

        self.retranslateUi(MyMusicPlayer)
        QtCore.QMetaObject.connectSlotsByName(MyMusicPlayer)
        MyMusicPlayer.setTabOrder(self.voice, self.horizontalSlider)
        MyMusicPlayer.setTabOrder(self.horizontalSlider, self.before_btn)
        MyMusicPlayer.setTabOrder(self.before_btn, self.next_btn)
        MyMusicPlayer.setTabOrder(self.next_btn, self.input_btn)
        MyMusicPlayer.setTabOrder(self.input_btn, self.play_btn)
        MyMusicPlayer.setTabOrder(self.play_btn, self.listWidget)

    def retranslateUi(self, MyMusicPlayer):
        _translate = QtCore.QCoreApplication.translate
        MyMusicPlayer.setWindowTitle(_translate("MyMusicPlayer", "MyMusicPlayer"))
        self.play_btn.setText(_translate("MyMusicPlayer", "play"))
        self.before_btn.setText(_translate("MyMusicPlayer", "before"))
        self.next_btn.setText(_translate("MyMusicPlayer", "next"))
        self.input_btn.setText(_translate("MyMusicPlayer", "fileinput"))
        self.played_time_lab.setText(_translate("MyMusicPlayer", "00:00"))
        self.len_time_lab.setText(_translate("MyMusicPlayer", "00:00"))
        self.order_list.setItemText(0, _translate("MyMusicPlayer", "单曲播放"))
        self.order_list.setItemText(1, _translate("MyMusicPlayer", "单曲循环"))
        self.order_list.setItemText(2, _translate("MyMusicPlayer", "顺序播放"))
        self.order_list.setItemText(3, _translate("MyMusicPlayer", "顺序循环"))
        self.order_list.setItemText(4, _translate("MyMusicPlayer", "随机播放"))
